fix(common): Fix NOTES always showing ingress protocol as http
bjw-s/helm-charts pull request #62
Opened 2022-10-20 17:21 UTC by gabe565

**Description of the change**

NOTES generation inconsistently uses `$protocol` and `$prefix` to add the protocol to the output URL. This causes ingresses to always show as `http://...`. This PR removes the `$protocol` var and uses `$prefix` to match the behavior of NOTES when ingress is disabled.

**Benefits**

NOTES will give a more accurate deployment URL.

**Possible drawbacks**

Slight change to NOTES output, which is currently always `http`.

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [x] Title of the PR conforms to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [x] Scope of the of the PR title contains the chart name.
- [x] Chart version in `Chart.yaml` has been bumped according to [Semantic Versioning](https://semver.org/).
- [x] Chart `artifacthub.io/changes` changelog annotation has been updated in `Chart.yaml`. See [Artifact Hub documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations) for more info.
- [x] Variables have been documented in the `values.yaml` file.

2022-10-29 06:12 UTC, bjw-s requested changes
Good catch and thank you for submitting the PR! I've left a few remarks but otherwise the change looks good.

2022-10-29 06:12 UTC, bjw-s commented on charts/library/common/Chart.yaml
> +version: 0.3.1
```suggestion
version: 0.3.0
```

2022-10-29 06:12 UTC, bjw-s commented on charts/library/common/Chart.yaml
> +    - kind: fixed
Please don't remove the "old" changelog for the `development` branch.

2022-10-31 02:20 UTC, gabe565 commented
Thanks for the feedback! Wasn't aware of the development process but it makes sense now. Rebased my changes against the latest `development` branch.

2022-10-31 13:22 UTC, bjw-s approved these changes

2022-10-31 13:25 UTC, merged